version: "3.9"

services:

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: vendacar-keycloak
    command: [ "start-dev" ]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"

  postgres:
    image: postgres:17
    container_name: vendacar-db
    environment:
      POSTGRES_USER: vendacar
      POSTGRES_PASSWORD: vendacar
      POSTGRES_DB: vendacar
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  vendacar:
    build: .
    container_name: vendacar-app
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: vendacar
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: vendacar
      DB_USER: vendacar
      DB_PASSWORD: vendacar
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgdata:
